"""Add training_type to TrainingSession

Revision ID: 29f4b3876740
Revises: d4a0ce6a6bf1
Create Date: 2025-04-06 04:11:49.083136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f4b3876740'
down_revision = 'd4a0ce6a6bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_session', schema=None) as batch_op:
        batch_op.drop_column('training_type')

    # ### end Alembic commands ###
