"""Initial models

Revision ID: d4a0ce6a6bf1
Revises: 
Create Date: 2025-04-06 02:50:53.251167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a0ce6a6bf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_session_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_session_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_session_status'), ['status'], unique=False)

    op.create_table('sensor_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('output', sa.Float(), nullable=False),
    sa.Column('received_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['training_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_reading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_reading_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_reading_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_reading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_reading_timestamp'))
        batch_op.drop_index(batch_op.f('ix_sensor_reading_session_id'))

    op.drop_table('sensor_reading')
    with op.batch_alter_table('training_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_session_status'))
        batch_op.drop_index(batch_op.f('ix_training_session_start_time'))
        batch_op.drop_index(batch_op.f('ix_training_session_end_time'))

    op.drop_table('training_session')
    # ### end Alembic commands ###
